/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package me.rizaldijs.telepati.client.deprecated;

import me.rizaldijs.telepati.client.TelepatiClient;
import me.rizaldijs.telepati.common.TFQuiz;
import org.springframework.util.concurrent.ListenableFutureCallback;

import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.TimerTask;
import java.util.concurrent.ExecutionException;
import javax.swing.*;

/**
 * @author Reinhart
 */
public class UserGUI extends JFrame {

    /**
     * Creates new form UserGUI
     */
    public UserGUI() {
        initComponents();
        txtLog.setEnabled(false);
        jRadioButton1.setVisible(false);
        jRadioButton2.setVisible(false);
        stopButton.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new JLabel();
        startButton = new JButton();
        jScrollPane1 = new JScrollPane();
        txtLog = new JTextArea();
        jRadioButton1 = new JRadioButton();
        jRadioButton2 = new JRadioButton();
        stopButton = new JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Cerdas Cermat");

        startButton.setText("Klik untuk memulai");
        startButton.addActionListener(new ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });

        txtLog.setColumns(20);
        txtLog.setRows(5);
        jScrollPane1.setViewportView(txtLog);

        jRadioButton1.setText("Benar");
        jRadioButton1.addActionListener(new ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        jRadioButton2.setText("Salah");
        jRadioButton2.addActionListener(new ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        stopButton.setText("Berhenti");
        stopButton.addActionListener(new ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopButtonActionPerformed(evt);
            }
        });

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(jScrollPane1))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(126, 126, 126)
                                                                .addComponent(jRadioButton1)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(jRadioButton2))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(159, 159, 159)
                                                                .addComponent(stopButton))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(129, 129, 129)
                                                                .addComponent(startButton)))
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap())
                        .addGroup(layout.createSequentialGroup()
                                .addGap(119, 119, 119)
                                .addComponent(jLabel1)
                                .addContainerGap(114, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(startButton)
                                .addGap(4, 4, 4)
                                .addComponent(stopButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 175, GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(jRadioButton1)
                                        .addComponent(jRadioButton2))
                                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void startButtonActionPerformed(ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed
        // TODO add your handling code here:
        this.txtLog.append("Memulai Tes \n");

        ListenableFutureCallback<TFQuiz> updateQuiz = new ListenableFutureCallback<TFQuiz>() {
            @Override
            public void onFailure(Throwable throwable) {
                txtLog.setText(throwable.getMessage());
            }

            @Override
            public void onSuccess(TFQuiz tfQuiz) {
                txtLog.setText(tfQuiz.getQuestion());
            }
        };


        try {
            this.client = new TelepatiClient(
                    "dadangeuy",
                    new QuizHandler(updateQuiz)
            );
            client.join();
        } catch (ExecutionException e) {
            e.printStackTrace();
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
//        task = new RunMeTask(this);
//        timer = new Timer();
//        timer.schedule(task, 5000, 10000);
//
//        this.INET_ADDR = "0.0.0.0";
//        this.PORT = 8888;
//
//        try {
//            serverSocket = new DatagramSocket();
//            addr = InetAddress.getByName(INET_ADDR);
//            this.txtLog.append("(Connecting to server at " + this.INET_ADDR + " with port " + this.PORT + ")");
//        } catch (Exception e) {
//
//        }
        startButton.setVisible(false);
        stopButton.setVisible(true);
        txtLog.setEnabled(true);

        jRadioButton1.setVisible(true);
        jRadioButton2.setVisible(true);
        ButtonGroup jawaban = new ButtonGroup();
        jawaban.add(jRadioButton1);
        jawaban.add(jRadioButton2);
        jawaban.clearSelection();
    }//GEN-LAST:event_startButtonActionPerformed

    private void jRadioButton1ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
        this.client.answer(true);
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
        this.client.answer(false);
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void stopButtonActionPerformed(ActionEvent evt) {//GEN-FIRST:event_stopButtonActionPerformed
        // TODO add your handling code here:
//        this.timer.cancel();
        this.txtLog.setText("");
        this.client.leave();
        stopButton.setVisible(false);
        startButton.setVisible(true);
        txtLog.setEnabled(false);
        jRadioButton1.setVisible(false);
        jRadioButton2.setVisible(false);
    }//GEN-LAST:event_stopButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JLabel jLabel1;
    private JRadioButton jRadioButton1;
    private JRadioButton jRadioButton2;
    private JScrollPane jScrollPane1;
    private JButton startButton;
    private JButton stopButton;
    private JTextArea txtLog;
    // End of variables declaration//GEN-END:variables
    private TelepatiClient client;

    public class RunMeTask extends TimerTask {

        private JTextArea myLog;
        int i = 0;

        UserGUI guiInduk;


        public RunMeTask(UserGUI gui) {

            this.guiInduk = gui;
        }

        public RunMeTask(JTextArea log) {

            this.myLog = log;
        }


        public void kirimPesan() {

        }


        @Override
        public void run() {
            //System.out.println("Run Me ~" + i);
            //this.myLog.append(i +". Timer runnning from run me task "+ "\n");

            kirimPesan();

        }
    }
}

////////////////////////////////////////////////////////////////////////////////